<a href="https://colab.research.google.com/github/Kevinsama115/Bigdata/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [6]:
(3-1)/(50-1)

0.04081632653061224

In [7]:
np.linspace(2,3,2)

array([2., 3.])

In [8]:
np.linspace(2,3,3)

array([2. , 2.5, 3. ])

In [9]:
np.linspace(2,3,3,retstep=True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [10]:
a = np.linspace(2,3,3,retstep=True)
a[1]

np.float64(0.5)

In [11]:
np.linspace(2,3,3,retstep=True,endpoint =False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [12]:
a=np.linspace(2,3,3, retstep=True)
float(a[1])

0.5

In [13]:
(3-2)/3

0.3333333333333333

Numpy 주요 함수

In [14]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
np.full([2,4],10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [22]:
np.full([3,5],10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [25]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [26]:
np.full([4,3], 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [27]:
np.empty(3)

array([2.        , 2.33333333, 2.66666667])

고급 색인


In [29]:
import numpy as np
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[1]

np.int64(1)

In [32]:
x[:5]

array([0, 1, 2, 3, 4])

In [33]:
x[[2]]

array([2])

In [34]:
x[[2,3]]

array([2, 3])

In [35]:
x[[2,3,2,5,8]]

array([2, 3, 2, 5, 8])

In [38]:
x= np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [39]:
int(x[0,1])

1

In [40]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [41]:
x[0,1]

np.int64(1)

In [42]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [43]:
x[[1,3,5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])