<a href="https://colab.research.google.com/github/Kevinsama115/Bigdata/blob/main/04w_array_stack_spilt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
c = np.arange(1,6,2)
c

array([1, 3, 5])

In [ ]:
import numpy as np
np.hstack((a,np.expand)

In [10]:
np.column_stack((a,c))


array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [11]:
import numpy as np
a= np.array([1,2,3]  )
b=np.array([4,5,6])
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
x= np.array([1,2,3])
y= np.array([4,5,6])
x

array([1, 2, 3])

In [13]:
y

array([4, 5, 6])

In [16]:
x.shape, y.shape

((3,), (3,))

In [17]:
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
np.c_[x, np.full(x.shape, 10), np.full(x.shape, 20), y]

array([[ 1, 10, 20,  4],
       [ 2, 10, 20,  5],
       [ 3, 10, 20,  6]])

In [24]:
from IPython.utils.path import random
import numpy as np
rg = np.random.default_rng (12345)
r = rg.random()
r

0.22733602246716966

In [25]:
rg.random()
r

0.22733602246716966

In [26]:
rg.random(4)

array([0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [27]:
rg.random((4,3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [28]:
import numpy as np
rg=np.random.default_rng(12345)
r=rg.integers(low=0,high=10,size=3)
r

array([6, 2, 7])

In [29]:
 rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [30]:
import numpy as np
rg = np.random.default_rng(1)
rg.standard_normal(3)

array([0.34558419, 0.82161814, 0.33043708])

In [32]:
rg.standard_normal((4,3))

array([[-1.30315723,  0.90535587,  0.44637457],
       [-0.53695324,  0.5811181 ,  0.3645724 ],
       [ 0.2941325 ,  0.02842224,  0.54671299],
       [-0.73645409, -0.16290995, -0.48211931]])

In [33]:
import numpy as np
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [34]:
rg.standard_normal((4,3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])

배열 결합 연습


In [35]:
a = np.arange(1,4)
b=np.arange(4,7)
c=np.arange(7,10)
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [36]:
p=np.arange(1,7).reshape(2,3)
q=np.arange(11,17).reshape(2,3)
r =np.arange(21,27).reshape(2,3)
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [38]:
np.column_stack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [41]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.concatenate((a,b,c),axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.concatenate((p,q,r),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [44]:
np.concatenate((p,q,r),axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [45]:
np.concatenate((p,q,r),axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [46]:
np.c_[a,b,c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])